#!/bin/bash

function gitj() {

if [ $# -eq 0 ]
then
	echo "Tracks git repos and allows easy jumping to the local repository directories"
	echo "Usage: gitj [list] [add REPONAME REPODIR] [remove REPONAME]"
	echo "-----------------------------------------------------------"
	echo "list: list all defined repos"
	echo "add: add a repo to the list"
	echo "remove: remove a repo from the list"
	return 0
fi

local config_file_dir=$HOME/.config/gitj/list
if ! [ -d "$HOME/.config/gitj" ]
then
	mkdir "$HOME/.config/gitj"
fi
touch "$config_file_dir"


local temp=$(sort -u -k1,1 "$config_file_dir")
echo "$temp" > "$config_file_dir"
local repo_name_list=$(cut -f 1 $config_file_dir)
local repo_dir_list=$(cut -f 2 $config_file_dir)

# JUMPING
if [ $# -eq 1 ]
then
	local target_repo_name=$1
	local repo_name_occurrence=$(cat "$config_file_dir" | egrep "$target_repo_name")
	if [ -z "$repo_name_occurrence" ]
	then
		echo "Error: Repository name not found"
		return 1
	fi

	local repo_directory=$(echo "$repo_name_occurrence" | cut -f 2)
	cd $repo_directory
	return 0
fi


}
